import { Button } from '@/components/ui/button'
import { Dumbbell, Users, Brain, TrendingUp } from 'lucide-react'

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-primary-50 to-white">
      {/* Header */}
      <header className="container mx-auto px-4 py-6 flex justify-between items-center">
        <div className="flex items-center space-x-2">
          <Dumbbell className="h-8 w-8 text-primary-600" />
          <span className="text-2xl font-bold text-gray-900">FitForge</span>
        </div>
        <div className="space-x-4">
          <Button variant="outline">Login</Button>
          <Button>Get Started</Button>
        </div>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-20 text-center">
        <h1 className="text-5xl font-bold text-gray-900 mb-6">
          Forge Your Fitness Journey with
          <span className="text-primary-600"> AI-Powered</span> Workouts
        </h1>
        <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
          Create personalized workout plans, track your progress, and get intelligent coaching. 
          Join a community of fitness enthusiasts and transform your training with FitForge.
        </p>
        <div className="space-x-4">
          <Button size="lg" className="bg-primary-600 hover:bg-primary-700">
            Start Free Trial
          </Button>
          <Button size="lg" variant="outline">
            View Demo
          </Button>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-20">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Everything You Need to Succeed
          </h2>
          <p className="text-lg text-gray-600">
            Powerful features designed to help you reach your fitness goals
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div className="text-center p-6 bg-white rounded-lg shadow-sm">
            <Brain className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-semibold mb-2">AI Workout Plans</h3>
            <p className="text-gray-600">
              Get personalized workout routines generated by AI based on your goals and experience
            </p>
          </div>
          
          <div className="text-center p-6 bg-white rounded-lg shadow-sm">
            <TrendingUp className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-semibold mb-2">Progress Tracking</h3>
            <p className="text-gray-600">
              Monitor your performance with detailed analytics and AI-powered insights
            </p>
          </div>
          
          <div className="text-center p-6 bg-white rounded-lg shadow-sm">
            <Users className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-semibold mb-2">Social Community</h3>
            <p className="text-gray-600">
              Connect with others, share workouts, and stay motivated through social features
            </p>
          </div>
          
          <div className="text-center p-6 bg-white rounded-lg shadow-sm">
            <Dumbbell className="h-12 w-12 text-primary-600 mx-auto mb-4" />
            <h3 className="text-xl font-semibold mb-2">Exercise Library</h3>
            <p className="text-gray-600">
              Access hundreds of exercises with detailed instructions and form tips
            </p>
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section className="container mx-auto px-4 py-20 bg-gray-50">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Choose Your Plan
          </h2>
          <p className="text-lg text-gray-600">
            Start free and upgrade when you're ready for more features
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 gap-8 max-w-4xl mx-auto">
          <div className="bg-white p-8 rounded-lg shadow-sm">
            <h3 className="text-2xl font-bold mb-2">Free</h3>
            <p className="text-4xl font-bold text-primary-600 mb-6">
              $0<span className="text-lg font-normal text-gray-600">/month</span>
            </p>
            <ul className="space-y-3 mb-8">
              <li className="flex items-center">
                <span className="text-green-500 mr-2">✓</span>
                3 active workout plans
              </li>
              <li className="flex items-center">
                <span className="text-green-500 mr-2">✓</span>
                Basic progress tracking
              </li>
              <li className="flex items-center">
                <span className="text-green-500 mr-2">✓</span>
                Exercise library access
              </li>
              <li className="flex items-center">
                <span className="text-green-500 mr-2">✓</span>
                Community features
              </li>
            </ul>
            <Button variant="outline" className="w-full">
              Get Started
            </Button>
          </div>
          
          <div className="bg-primary-600 text-white p-8 rounded-lg shadow-lg">
            <h3 className="text-2xl font-bold mb-2">Pro</h3>
            <p className="text-4xl font-bold mb-6">
              $12<span className="text-lg font-normal opacity-80">/month</span>
            </p>
            <ul className="space-y-3 mb-8">
              <li className="flex items-center">
                <span className="text-green-300 mr-2">✓</span>
                Unlimited workout plans
              </li>
              <li className="flex items-center">
                <span className="text-green-300 mr-2">✓</span>
                AI workout generation
              </li>
              <li className="flex items-center">
                <span className="text-green-300 mr-2">✓</span>
                AI progress insights
              </li>
              <li className="flex items-center">
                <span className="text-green-300 mr-2">✓</span>
                AI form tips & coaching
              </li>
            </ul>
            <Button variant="secondary" className="w-full bg-white text-primary-600 hover:bg-gray-100">
              Start Free Trial
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="container mx-auto px-4 text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <Dumbbell className="h-6 w-6" />
            <span className="text-xl font-bold">FitForge</span>
          </div>
          <p className="text-gray-400">
            © 2024 FitForge. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  )
}
